# Site settings
title: Luke Blog
SEOTitle: Nash Equilibrium | Hy Blog
header-img: img/home-bg7.jpg
email: heyan.swufe@gmail.com
description: "全都在别处，大群的驯鹿。"
keyword: "何颜, Heyan, risk, machine learning, statistics, finance, R, Python"
url: "https://yanheluke.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     1742729010
zhihu_username:     nash_90
github_username:    yanheluke
#twitter_username:
#facebook_username:
# linkedin_username:  firstname-lastname-idxxxx


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username:

# Netease setttings
netease_comment: false


## 统计
# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

## Google Analytics
ga_track_id: 'UA-61699906-2'            # Format: UA-xxxxxx-xx
ga_domain: yanheluke.github.io

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 18186e1968a6b84191a4                            #生成的clientID
  clientSecret: 251ac585a8b2fe3807ffdbfaf490a20ba4e172e6    #生成的clientSecret
  repo: yanheluke.github.io    #仓库名称
  owner: yanheluke    #github用户名
  admin: yanheluke
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Risk | Finance | Statistics |<br>Machine Learning | 科幻 | 游戏 | J-Pop | 摄影小白 <br>贝克兰德魔术和戏剧表演的保护者。"
sidebar-avatar: /img/avatar-heyan-4.PNG      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "HaoZ",
        href: "https://haoz.dev/"
    # },{
    #     title: "前端外刊评论",
    #     href: "http://qianduan.guru/"
    # },{
    #     title: "天镶的博客",
    #     href: "http://lingyu.wang/"
    # },{
    #     title: "Luke 的自留地",
    #     href: "http://hmqk1995.github.io"
    # },{
    #     title: "Ebn's Blog",
    #     href: "http://ebnbin.com/"
    # },{
    #     title: "SmdCn's Blog",
    #     href: "http://blog.smdcn.net"
    # },{
    #     title: "David's Game",
    #     href: "https://www.ruoyaowu.com/"
    # },{
    #     title: "DHong Say",
    #     href: "http://dhong.co"
    # },{
    #     title: "尹峰以为",
    #     href: "http://ingf.github.io/"
    # },{
    #     title: "解旻的博客",
    #     href: "http://xieminis.me/"
    }
]
